"""Hardware-free tests for D500 protocol and drone-frame coordinates."""

from __future__ import annotations

import math
from pathlib import Path
import struct
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from components.radar_driver import (  # noqa: E402
    D500PacketParser,
    D500RadarComponent,
    DroneGlobalAlignment,
    ICPResult,
    ICPScanMatcher,
    Pose2D,
    RadarMount,
    RadarOdometry,
    RadarOdometryUpdate,
    RadarPacket,
    RadarPoint,
    RadarScan,
    RadarScanAssembler,
    RectangleFieldCalibrator,
    RectangularWallReference,
    WallFusionConfig,
    WallFusionStatus,
    WallLineConfig,
    WallLineLocalizer,
    WallPoseObservation,
    calculate_d500_crc8,
    fuse_wall_observation,
    rotate_cw,
    scan_points_in_drone_global,
)


def build_frame(*, start_centideg: int = 1000, stop_centideg: int = 2100) -> bytes:
    values: list[int] = [3600, start_centideg]
    for index in range(12):
        values.extend((1000 + index, 80 + index))
    values.extend((stop_centideg, 1234))
    payload = struct.pack("<HH" + "HB" * 12 + "HH", *values)
    frame_without_crc = b"\x54\x2c" + payload
    return frame_without_crc + bytes((calculate_d500_crc8(frame_without_crc),))


class D500ProtocolTests(unittest.TestCase):
    def test_crc_matches_drone_reference_table_vector(self) -> None:
        # Expected value generated by FlightController/Components/Utils.py.
        self.assertEqual(build_frame()[-1], 0xE7)

    def test_incremental_decode_and_angles(self) -> None:
        frame = build_frame()
        parser = D500PacketParser()
        self.assertEqual(parser.feed(b"noise" + frame[:10]), [])
        packets = parser.feed(frame[10:])
        self.assertEqual(len(packets), 1)
        packet = packets[0]
        self.assertEqual(packet.rotation_speed_deg_s, 3600)
        self.assertEqual(packet.timestamp_ms, 1234)
        self.assertEqual(packet.points[0].angle_cw_deg, 10.0)
        self.assertEqual(packet.points[-1].angle_cw_deg, 21.0)
        self.assertEqual(packet.points[5].distance_mm, 1005)
        self.assertEqual(parser.stats.decoded_frames, 1)
        self.assertEqual(parser.stats.discarded_bytes, 5)

    def test_bad_crc_resynchronizes_to_following_frame(self) -> None:
        bad = bytearray(build_frame())
        bad[10] ^= 0x40
        good = build_frame(start_centideg=2200, stop_centideg=3300)
        parser = D500PacketParser()
        packets = parser.feed(bytes(bad) + good)
        self.assertEqual(len(packets), 1)
        self.assertEqual(packets[0].start_angle_cw_deg, 22.0)
        self.assertEqual(parser.stats.crc_errors, 1)

    def test_scan_assembler_emits_at_angle_wrap(self) -> None:
        first_points = tuple(RadarPoint(300 + index * 5, 1000, 100) for index in range(12))
        middle_points = tuple(RadarPoint(index * 5, 1000, 100) for index in range(12))
        final_points = tuple(RadarPoint(300 + index * 5, 1000, 100) for index in range(12))
        next_points = tuple(RadarPoint(index * 5, 1000, 100) for index in range(12))
        assembler = RadarScanAssembler(min_points=10)
        first = RadarPacket(3600, 300, 355, 10, first_points)
        second = RadarPacket(3600, 0, 55, 20, middle_points)
        final = RadarPacket(3600, 300, 355, 30, final_points)
        following = RadarPacket(3600, 0, 55, 40, next_points)
        self.assertEqual(assembler.feed(first), [])
        self.assertEqual(assembler.feed(second), [])  # First wrap discards startup partial scan.
        self.assertEqual(assembler.feed(final), [])
        scans = assembler.feed(following)
        self.assertEqual(len(scans), 1)
        self.assertEqual(len(scans[0].points), 24)

    def test_scan_assembler_defaults_reject_noise_and_unusable_range(self) -> None:
        assembler = RadarScanAssembler()
        self.assertEqual(assembler.min_distance_mm, 100)
        self.assertEqual(assembler.max_distance_mm, 6500)
        self.assertEqual(assembler.min_confidence, 30)


class DroneCoordinateTests(unittest.TestCase):
    def assertPointAlmostEqual(self, actual, expected, places=6) -> None:
        self.assertAlmostEqual(actual[0], expected[0], places=places)
        self.assertAlmostEqual(actual[1], expected[1], places=places)

    def test_raw_angle_uses_forward_x_left_y_and_clockwise_positive(self) -> None:
        point = RadarPoint(90.0, 1000, 100)
        self.assertPointAlmostEqual(point.sensor_xy_cm(), (0.0, -100.0))

    def test_radar_mount_rotation_and_offset(self) -> None:
        mount = RadarMount(x_forward_cm=10, y_left_cm=3, yaw_cw_deg=90)
        self.assertPointAlmostEqual(mount.sensor_to_body((100, 0)), (10, -97))

    def test_reference_pose_maps_exactly_into_drone_global(self) -> None:
        car_reference = Pose2D(100, 20, 90)
        drone_reference = Pose2D(1000, 2000, -90)
        alignment = DroneGlobalAlignment.from_reference(car_reference, drone_reference)
        transformed = alignment.pose_to_global(car_reference)
        self.assertAlmostEqual(transformed.x_cm, drone_reference.x_cm)
        self.assertAlmostEqual(transformed.y_cm, drone_reference.y_cm)
        self.assertAlmostEqual(transformed.yaw_cw_deg, drone_reference.yaw_cw_deg)
        self.assertAlmostEqual(abs(alignment.yaw_offset_cw_deg), 180.0)

    def test_global_alignment_inverse_round_trip(self) -> None:
        alignment = DroneGlobalAlignment(120, -45, 73)
        local = Pose2D(32, -18, -125)
        recovered = alignment.pose_to_local(alignment.pose_to_global(local))
        self.assertAlmostEqual(recovered.x_cm, local.x_cm)
        self.assertAlmostEqual(recovered.y_cm, local.y_cm)
        self.assertAlmostEqual(recovered.yaw_cw_deg, local.yaw_cw_deg)

    def test_scan_points_are_written_in_drone_global_frame(self) -> None:
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        car_pose = Pose2D(10, 20, 90)
        mount = RadarMount()
        alignment = DroneGlobalAlignment(1000, 2000, 90)
        points = scan_points_in_drone_global(scan, car_pose, mount, alignment)
        # Sensor +X -> car-local -Y at car yaw 90; then -> drone-global -X.
        self.assertPointAlmostEqual(points[0], (920, 1990))


class ICPTests(unittest.TestCase):
    def test_recovers_clockwise_current_to_reference_transform(self) -> None:
        current = [
            (35 * math.cos(i * 0.37) + i * 1.1, 28 * math.sin(i * 0.53) - i * 0.4)
            for i in range(80)
        ]
        reference = []
        for point in current:
            x_cm, y_cm = rotate_cw(*point, 3.0)
            reference.append((x_cm + 4.0, y_cm - 2.0))
        matcher = ICPScanMatcher(max_correspondence_cm=20, min_correspondences=30)
        result = matcher.match(reference, current)
        pose = result.transform_current_to_reference
        self.assertAlmostEqual(pose.x_cm, 4.0, delta=0.15)
        self.assertAlmostEqual(pose.y_cm, -2.0, delta=0.15)
        self.assertAlmostEqual(pose.yaw_cw_deg, 3.0, delta=0.15)
        self.assertLess(result.mean_error_cm, 0.15)

    def test_odometry_ignores_stationary_jitter_without_advancing_keyframe(self) -> None:
        class FixedMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(0.8, 0.3, 0.2), 80, 1.0, 2)

        odometry = RadarOdometry(matcher=FixedMatcher())
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        self.assertTrue(odometry.update(scan).accepted)
        keyframe = odometry._reference

        update = odometry.update(scan)

        self.assertTrue(update.accepted)
        self.assertEqual(update.pose, Pose2D())
        self.assertIs(odometry._reference, keyframe)

    def test_odometry_rejects_non_ackermann_lateral_jump(self) -> None:
        class FixedMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(5.0, 12.0, 0.0), 80, 1.0, 2)

        odometry = RadarOdometry(matcher=FixedMatcher())
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        odometry.update(scan)

        update = odometry.update(scan)

        self.assertFalse(update.accepted)
        self.assertEqual(update.rejection_reason, "Ackermann lateral gate")

    def test_stationary_motion_hint_freezes_large_icp_step(self) -> None:
        class FixedMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(2.5, 0.0, 0.0), 80, 1.0, 2)

        odometry = RadarOdometry(
            matcher=FixedMatcher(),
            stationary_grace_s=0.0,
        )
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        odometry.update(scan)
        odometry.set_motion_state(False)

        stationary = odometry.update(scan)

        self.assertTrue(stationary.accepted)
        self.assertEqual(stationary.pose, Pose2D())
        odometry.set_motion_state(True)
        moving = odometry.update(scan)
        self.assertAlmostEqual(moving.pose.x_cm, 2.5)

    def test_repeated_stationary_hint_does_not_prevent_reference_refresh(self) -> None:
        class SmallMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(0.1, 0.0, 0.0), 80, 1.0, 2)

        odometry = RadarOdometry(matcher=SmallMatcher(), stationary_grace_s=0.0)
        first = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        odometry.update(first)
        initial_reference = list(odometry._reference)
        odometry.set_motion_state(False)

        for timestamp in (1, 2, 3):
            odometry.set_motion_state(False)
            odometry.update(
                RadarScan((RadarPoint(timestamp, 1000, 100),), timestamp, 3600)
            )

        self.assertNotEqual(odometry._reference, initial_reference)

    def test_stop_grace_integrates_braking_coast(self) -> None:
        class FixedMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(2.5, 0.0, 0.0), 80, 1.0, 2)

        odometry = RadarOdometry(
            matcher=FixedMatcher(),
            stationary_grace_s=60.0,
        )
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        odometry.update(scan)
        odometry.set_motion_state(False)

        coast = odometry.update(scan)

        self.assertTrue(coast.accepted)
        self.assertAlmostEqual(coast.pose.x_cm, 2.5)

    def test_stationary_repeated_gate_rebases_reference_without_pose_jump(self) -> None:
        class SequencedMatcher:
            def __init__(self):
                self.results = iter(
                    (
                        ICPResult(Pose2D(20.0, 0.0, 0.0), 80, 1.0, 2),
                        ICPResult(Pose2D(20.0, 0.0, 0.0), 80, 1.0, 2),
                        ICPResult(Pose2D(20.0, 0.0, 0.0), 80, 1.0, 2),
                        ICPResult(Pose2D(0.1, 0.0, 0.0), 80, 1.0, 2),
                    )
                )

            def match(self, reference, current):
                return next(self.results)

        odometry = RadarOdometry(
            matcher=SequencedMatcher(),
            stationary_grace_s=0.0,
            stationary_rebase_rejections=3,
        )
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        odometry.update(scan)
        odometry.set_motion_state(False)

        first = odometry.update(scan)
        second = odometry.update(scan)
        rebased = odometry.update(scan)
        recovered = odometry.update(scan)

        self.assertFalse(first.accepted)
        self.assertFalse(second.accepted)
        self.assertFalse(rebased.accepted)
        self.assertIn("stationary ICP reference rebased", rebased.rejection_reason)
        self.assertTrue(recovered.accepted)
        self.assertEqual(recovered.pose, Pose2D())


def rectangular_wall_scan(pose_in_wall: Pose2D, *, include_right: bool = True) -> RadarScan:
    wall_points: list[tuple[float, float]] = []
    wall_points.extend((0.0, float(y_cm)) for y_cm in range(0, 205, 5))
    if include_right:
        wall_points.extend((float(x_cm), 0.0) for x_cm in range(0, 245, 5))
    radar_points = []
    for wall_x, wall_y in wall_points:
        relative_x = wall_x - pose_in_wall.x_cm
        relative_y = wall_y - pose_in_wall.y_cm
        body_x, body_y = rotate_cw(
            relative_x,
            relative_y,
            -pose_in_wall.yaw_cw_deg,
        )
        distance_cm = math.hypot(body_x, body_y)
        angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360.0
        radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))
    return RadarScan(tuple(radar_points), 0, 3600)


def selected_walls_scan(
    pose_in_wall: Pose2D,
    *,
    x_wall_cm: float,
    y_wall_cm: float,
) -> RadarScan:
    wall_points: list[tuple[float, float]] = []
    wall_points.extend((x_wall_cm, float(y_cm)) for y_cm in range(0, 205, 5))
    wall_points.extend((float(x_cm), y_wall_cm) for x_cm in range(0, 305, 5))
    radar_points: list[RadarPoint] = []
    for wall_x, wall_y in wall_points:
        relative_x = wall_x - pose_in_wall.x_cm
        relative_y = wall_y - pose_in_wall.y_cm
        body_x, body_y = rotate_cw(
            relative_x,
            relative_y,
            -pose_in_wall.yaw_cw_deg,
        )
        distance_cm = math.hypot(body_x, body_y)
        angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360.0
        radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))
    return RadarScan(tuple(radar_points), 0, 3600)


class WallLineFusionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.wall_to_global = DroneGlobalAlignment(500, 200, 90)
        self.reference = RectangularWallReference(self.wall_to_global)
        self.localizer = WallLineLocalizer(
            self.reference,
            config=WallLineConfig(min_points_per_wall=10, min_line_span_cm=40),
        )

    def test_wall_lines_recover_absolute_pose_from_drifted_prediction(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        observation = self.localizer.observe(
            rectangular_wall_scan(true_wall_pose),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )
        self.assertAlmostEqual(observation.x_cm, true_wall_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(observation.y_cm, true_wall_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_wall_pose.yaw_cw_deg, delta=1.0)
        self.assertGreaterEqual(observation.back_wall_points, 10)
        self.assertGreaterEqual(observation.right_wall_points, 10)

    def test_rotation_adaptation_localizes_a_highly_rotated_car(self) -> None:
        true_wall_pose = Pose2D(100, 80, 72)
        predicted_wall_pose = Pose2D(106, 75, 68)

        observation = self.localizer.observe(
            rectangular_wall_scan(true_wall_pose),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )

        self.assertAlmostEqual(observation.x_cm, true_wall_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(observation.y_cm, true_wall_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_wall_pose.yaw_cw_deg, delta=1.0)

        without_adaptation = WallLineLocalizer(
            self.reference,
            config=WallLineConfig(
                min_points_per_wall=10,
                min_line_span_cm=40,
                rotation_adaptation=False,
            ),
        ).observe(
            rectangular_wall_scan(true_wall_pose),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )
        self.assertEqual(without_adaptation.observed_axes, 0)

    def test_drone_absolute_profile_uses_per_scan_low_pass_correction(self) -> None:
        config = WallFusionConfig.drone_absolute(low_pass_ratio=0.60)

        self.assertEqual(config.update_every_scans, 1)
        self.assertEqual(config.consistency_samples, 3)
        self.assertAlmostEqual(config.position_gain, 0.60)
        self.assertAlmostEqual(config.yaw_gain, 0.60)
        self.assertEqual(config.max_position_residual_cm, 12.0)
        self.assertEqual(config.max_position_correction_cm, 5.0)

    def test_car_profile_limits_wall_correction_to_slow_drift(self) -> None:
        config = WallFusionConfig.car_slow_drift()

        self.assertEqual(config.update_every_scans, 5)
        self.assertEqual(config.consistency_samples, 3)
        self.assertAlmostEqual(config.position_gain, 0.20)
        self.assertAlmostEqual(config.yaw_gain, 0.15)
        self.assertEqual(config.max_position_residual_cm, 12.0)
        self.assertEqual(config.max_position_correction_cm, 1.0)
        self.assertEqual(config.max_yaw_correction_deg, 0.5)

    def test_drone_absolute_profile_rejects_parallel_line_jump_from_real_log(self) -> None:
        predicted_wall = Pose2D(92.0, 4.6, -32.0)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        false_parallel_line = WallPoseObservation(
            92.8,
            35.1,
            -32.1,
            100,
            84,
            3.24,
            2.67,
        )

        result = fuse_wall_observation(
            predicted_global,
            false_parallel_line,
            self.reference,
            WallFusionConfig.drone_absolute(),
        )

        self.assertFalse(result.accepted)
        self.assertIs(result.status, WallFusionStatus.HARD_REJECTED)
        self.assertIn("wall Y residual gate", result.reason or "")

    def test_partial_back_wall_corrects_x_but_not_y(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        observation = self.localizer.observe(
            rectangular_wall_scan(true_wall_pose, include_right=False),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )
        self.assertIsNotNone(observation.x_cm)
        self.assertIsNone(observation.y_cm)
        self.assertIsNotNone(observation.yaw_cw_deg)

    def test_front_and_left_walls_are_used_when_they_are_nearest(self) -> None:
        reference = RectangularWallReference(
            self.wall_to_global,
            back_wall_x_cm=0.0,
            right_wall_y_cm=0.0,
            front_wall_x_cm=300.0,
            left_wall_y_cm=200.0,
        )
        localizer = WallLineLocalizer(
            reference,
            config=WallLineConfig(min_points_per_wall=10, min_line_span_cm=40),
        )
        true_pose = Pose2D(265.0, 165.0, 8.0)
        predicted_pose = Pose2D(270.0, 160.0, 11.0)

        observation = localizer.observe(
            selected_walls_scan(
                true_pose,
                x_wall_cm=300.0,
                y_wall_cm=200.0,
            ),
            self.wall_to_global.pose_to_global(predicted_pose),
        )

        self.assertAlmostEqual(observation.x_cm, true_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(observation.y_cm, true_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_pose.yaw_cw_deg, delta=1.0)

    def test_real_wall_cluster_wins_over_denser_parallel_interior_line(self) -> None:
        true_pose = Pose2D(100.0, 80.0, 0.0)
        wall_points: list[tuple[float, float]] = []
        wall_points.extend((0.0, float(y_cm)) for y_cm in range(0, 205, 5))
        wall_points.extend((float(x_cm), 0.0) for x_cm in range(0, 305, 5))
        # This is the failure shape from the vehicle log: a denser horizontal
        # structure sits 18 cm inboard but remains inside the 45 cm wall gate.
        wall_points.extend((float(x_cm), 18.0) for x_cm in range(0, 305, 2))
        radar_points: list[RadarPoint] = []
        for wall_x, wall_y in wall_points:
            body_x = wall_x - true_pose.x_cm
            body_y = wall_y - true_pose.y_cm
            distance_cm = math.hypot(body_x, body_y)
            angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360.0
            radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))

        observation = self.localizer.observe(
            RadarScan(tuple(radar_points), 0, 3600),
            self.wall_to_global.pose_to_global(true_pose),
        )

        self.assertAlmostEqual(observation.y_cm, true_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_pose.yaw_cw_deg, delta=1.0)

    def test_fusion_applies_limited_correction(self) -> None:
        predicted_wall = Pose2D(110, 70, 20)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(100, 80, 10, 20, 20, 1, 1)
        result = fuse_wall_observation(
            predicted_global,
            observation,
            self.reference,
            WallFusionConfig(
                position_gain=0.25,
                yaw_gain=0.5,
                max_position_correction_cm=5.0,
                max_yaw_correction_deg=10.0,
            ),
        )
        self.assertTrue(result.accepted)
        fused_wall = self.wall_to_global.pose_to_local(result.fused_global_pose)
        self.assertAlmostEqual(fused_wall.x_cm, 107.5)
        self.assertAlmostEqual(fused_wall.y_cm, 72.5)
        self.assertAlmostEqual(fused_wall.yaw_cw_deg, 15)

    def test_large_false_wall_residual_is_rejected(self) -> None:
        predicted_wall = Pose2D(100, 80, 10)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(300, 80, 10, 20, 20, 1, 1)
        result = fuse_wall_observation(predicted_global, observation, self.reference)
        self.assertFalse(result.accepted)
        self.assertEqual(result.fused_global_pose, predicted_global)
        self.assertIn("residual gate", result.reason)

    def test_large_valid_correction_is_clamped_instead_of_rejected(self) -> None:
        predicted_wall = Pose2D(130, 110, 18)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(100, 80, 10, 30, 30, 1, 1)

        result = fuse_wall_observation(
            predicted_global,
            observation,
            self.reference,
            WallFusionConfig(
                position_gain=0.20,
                yaw_gain=0.15,
                max_position_correction_cm=2.0,
                max_yaw_correction_deg=0.5,
            ),
        )

        self.assertTrue(result.accepted)
        self.assertAlmostEqual(
            math.hypot(result.correction_x_cm, result.correction_y_cm),
            2.0,
        )
        self.assertAlmostEqual(abs(result.correction_yaw_deg), 0.5)
        self.assertAlmostEqual(result.residual_x_cm, -30.0)
        self.assertAlmostEqual(result.residual_y_cm, -30.0)

    def test_component_writes_wall_correction_back_into_odometry(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        scan = rectangular_wall_scan(true_wall_pose)

        class OneScanAssembler:
            def feed(self, packet):
                return [scan]

        class FixedOdometry:
            def __init__(self):
                self.pose = predicted_wall_pose

            def update(self, incoming_scan):
                return RadarOdometryUpdate(self.pose, True, True)

        odometry = FixedOdometry()
        component = D500RadarComponent(
            alignment=self.wall_to_global,
            assembler=OneScanAssembler(),
            odometry=odometry,
            wall_localizer=self.localizer,
            wall_fusion_config=WallFusionConfig(
                update_every_scans=1,
                position_gain=1.0,
                yaw_gain=1.0,
                max_position_correction_cm=20.0,
                max_yaw_correction_deg=10.0,
                consistency_samples=1,
            ),
        )
        dummy_packet = RadarPacket(3600, 0, 1, 0, ())
        update = component.process_packet(dummy_packet)[0]
        self.assertIsNotNone(update.wall_fusion)
        self.assertTrue(update.wall_fusion.accepted)
        corrected_wall = self.wall_to_global.pose_to_local(update.global_pose)
        self.assertAlmostEqual(corrected_wall.x_cm, true_wall_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(corrected_wall.y_cm, true_wall_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(corrected_wall.yaw_cw_deg, true_wall_pose.yaw_cw_deg, delta=1.0)
        self.assertEqual(odometry.pose, update.odometry.pose)
        self.assertGreater(len(update.global_points_cm), 0)

    def test_component_requires_repeated_consistent_wall_observations(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        scan = rectangular_wall_scan(true_wall_pose)

        class OneScanAssembler:
            def feed(self, packet):
                return [scan]

        class FixedOdometry:
            def __init__(self):
                self.pose = predicted_wall_pose

            def update(self, incoming_scan):
                return RadarOdometryUpdate(self.pose, True, True)

        component = D500RadarComponent(
            alignment=self.wall_to_global,
            assembler=OneScanAssembler(),
            odometry=FixedOdometry(),
            wall_localizer=self.localizer,
            wall_fusion_config=WallFusionConfig(
                update_every_scans=1,
                consistency_samples=3,
                max_position_correction_cm=20.0,
                max_yaw_correction_deg=10.0,
            ),
        )
        packet = RadarPacket(3600, 0, 1, 0, ())

        first = component.process_packet(packet)[0]
        second = component.process_packet(packet)[0]
        third = component.process_packet(packet)[0]

        self.assertFalse(first.wall_fusion.accepted)
        self.assertFalse(second.wall_fusion.accepted)
        self.assertTrue(third.wall_fusion.accepted)

    def test_moving_absolute_observations_accept_stable_residual(self) -> None:
        identity = DroneGlobalAlignment(0.0, 0.0, 0.0)
        reference = RectangularWallReference(identity)
        scan = RadarScan((), 0, 0)

        class OneScanAssembler:
            def feed(self, packet):
                return [scan]

        class MovingOdometry:
            def __init__(self):
                self.pose = Pose2D()
                self._poses = iter((Pose2D(0, 0, 0), Pose2D(3, 0, 0), Pose2D(6, 0, 0)))

            def update(self, incoming_scan):
                self.pose = next(self._poses)
                return RadarOdometryUpdate(self.pose, True, True)

        class MovingWallLocalizer:
            def __init__(self):
                self.reference = reference
                self._observations = iter(
                    (
                        WallPoseObservation(5, None, 0, 30, 0, 1.0, None),
                        WallPoseObservation(8, None, 0, 30, 0, 1.0, None),
                        WallPoseObservation(11, None, 0, 30, 0, 1.0, None),
                    )
                )

            def observe(self, incoming_scan, predicted_global_pose):
                return next(self._observations)

        component = D500RadarComponent(
            alignment=identity,
            assembler=OneScanAssembler(),
            odometry=MovingOdometry(),
            wall_localizer=MovingWallLocalizer(),
            wall_fusion_config=WallFusionConfig(
                update_every_scans=1,
                consistency_samples=3,
                position_gain=1.0,
                max_position_correction_cm=20.0,
                max_yaw_correction_deg=10.0,
            ),
        )
        packet = RadarPacket(3600, 0, 1, 0, ())

        first = component.process_packet(packet)[0]
        second = component.process_packet(packet)[0]
        third = component.process_packet(packet)[0]

        self.assertIs(first.wall_fusion.status, WallFusionStatus.PENDING)
        self.assertIs(second.wall_fusion.status, WallFusionStatus.PENDING)
        self.assertTrue(third.wall_fusion.accepted)
        self.assertAlmostEqual(third.wall_fusion.residual_x_cm, 5.0)
        self.assertAlmostEqual(third.global_pose.x_cm, 11.0)

    def test_missing_y_axis_does_not_reset_x_residual_consensus(self) -> None:
        identity = DroneGlobalAlignment(0.0, 0.0, 0.0)
        reference = RectangularWallReference(identity)
        component = D500RadarComponent(
            alignment=identity,
            wall_fusion_config=WallFusionConfig(consistency_samples=3),
        )
        observations = (
            (Pose2D(0, 0, 0), WallPoseObservation(5, 4, 0, 30, 30, 1, 1)),
            (Pose2D(3, 0, 0), WallPoseObservation(8, None, 0, 30, 0, 1, None)),
            (Pose2D(6, 0, 0), WallPoseObservation(11, 4, 0, 30, 30, 1, 1)),
        )

        result = None
        for predicted, observation in observations:
            consensus, diagnostic = component._wall_residual_consensus_observation(
                observation,
                predicted,
                reference,
                component.wall_fusion_config,
            )
            result = (consensus, diagnostic)

        consensus, diagnostic = result
        self.assertIsNotNone(consensus)
        self.assertAlmostEqual(consensus.x_cm, 11.0)
        self.assertIsNone(consensus.y_cm)
        self.assertEqual(diagnostic.x_consensus_samples, 3)
        self.assertEqual(diagnostic.y_consensus_samples, 2)

    def test_weak_twelve_point_wall_is_not_used_for_correction(self) -> None:
        identity = DroneGlobalAlignment(0.0, 0.0, 0.0)
        reference = RectangularWallReference(identity)
        component = D500RadarComponent(
            alignment=identity,
            wall_fusion_config=WallFusionConfig(consistency_samples=1),
        )

        consensus, diagnostic = component._wall_residual_consensus_observation(
            WallPoseObservation(None, -14.5, 0, 0, 12, None, 0.5),
            Pose2D(),
            reference,
            component.wall_fusion_config,
        )

        self.assertIsNone(consensus)
        self.assertIs(diagnostic.status, WallFusionStatus.NO_OBSERVATION)


class RectangleStartupCalibrationTests(unittest.TestCase):
    def test_initial_position_is_origin_and_nearest_edge_becomes_x_axis(self) -> None:
        edge_ccw_from_car = 20.0
        wall_points = []
        for y_cm in range(-90, 131, 5):
            wall_points.extend(((-120, y_cm), (180, y_cm)))
        for x_cm in range(-120, 181, 5):
            wall_points.extend(((x_cm, -90), (x_cm, 130)))
        radar_points = []
        for global_x, global_y in wall_points:
            body_x, body_y = rotate_cw(
                global_x,
                global_y,
                -edge_ccw_from_car,
            )
            distance_cm = math.hypot(body_x, body_y)
            angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360
            radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))
        scan = RadarScan(tuple(radar_points), 0, 3600)

        calibration = RectangleFieldCalibrator().calibrate([scan])
        self.assertAlmostEqual(calibration.initial_global_pose.x_cm, 0, delta=0.1)
        self.assertAlmostEqual(calibration.initial_global_pose.y_cm, 0, delta=0.1)
        self.assertAlmostEqual(
            calibration.selected_edge_ccw_from_car_deg,
            edge_ccw_from_car,
            delta=0.2,
        )
        self.assertAlmostEqual(calibration.min_x_cm, -120, delta=0.5)
        self.assertAlmostEqual(calibration.max_x_cm, 180, delta=0.5)
        self.assertAlmostEqual(calibration.min_y_cm, -90, delta=0.5)
        self.assertAlmostEqual(calibration.max_y_cm, 130, delta=0.5)


if __name__ == "__main__":
    unittest.main()
