"""Lazy exports for shared hardware and communication components."""

from importlib import import_module as _import_module

_EXPORT_MODULES = {
    'ChassisCommand': 'rear_motor',
    'DriverStateError': 'rear_motor',
    'MotorDirection': 'rear_motor',
    'RearMotorDriver': 'rear_motor',
    'UnsupportedWheelCommand': 'rear_motor',
    'WheelSpeeds': 'rear_motor',
    'build_velocity_frame': 'rear_motor',
    'wheel_speeds_to_chassis': 'rear_motor',
    'BridgeCodecStats': 'serial_communication',
    'DEFAULT_HC14_PORT': 'serial_communication',
    'FCWirelessBridgeCodec': 'serial_communication',
    'HC14SerialDriver': 'serial_communication',
    'SerialCommunicationDriver': 'serial_communication',
    'SerialDriverError': 'serial_communication',
    'AlarmGPIOError': 'sound_light_alarm',
    'SoundLightAlarm': 'sound_light_alarm',
    'alarm_off': 'sound_light_alarm',
    'alarm_on': 'sound_light_alarm',
    'resolve_gpio_number': 'sound_light_alarm',
    'BatteryVoltageSample': 'battery_voltage_monitor',
    'C10BBatteryVoltageReader': 'battery_voltage_monitor',
    'C10BTelemetryError': 'battery_voltage_monitor',
    'C10BTelemetryFrame': 'battery_voltage_monitor',
    'C10BTelemetryParser': 'battery_voltage_monitor',
    'LowBatteryMonitor': 'battery_voltage_monitor',
    'decode_stock_c10b_voltage_v': 'battery_voltage_monitor',
    'DEFAULT_D500_PORT': 'radar_driver',
    'D500PacketParser': 'radar_driver',
    'D500RadarComponent': 'radar_driver',
    'D500SerialDriver': 'radar_driver',
    'DroneGlobalAlignment': 'radar_driver',
    'DroneGlobalPointMap': 'radar_driver',
    'GlobalCorrectionMode': 'radar_driver',
    'ICPResult': 'radar_driver',
    'ICPScanMatcher': 'radar_driver',
    'Pose2D': 'radar_driver',
    'RadarDriver': 'radar_driver',
    'RadarDriverError': 'radar_driver',
    'RadarLocalizationUpdate': 'radar_driver',
    'RadarMount': 'radar_driver',
    'RadarOdometry': 'radar_driver',
    'RadarPacket': 'radar_driver',
    'RadarPoint': 'radar_driver',
    'RadarScan': 'radar_driver',
    'RadarScanAssembler': 'radar_driver',
    'RectangleCalibrationConfig': 'radar_driver',
    'RectangleFieldCalibration': 'radar_driver',
    'RectangleFieldCalibrator': 'radar_driver',
    'RectangularWallReference': 'radar_driver',
    'WallFusionConfig': 'radar_driver',
    'WallFusionResult': 'radar_driver',
    'WallFusionStatus': 'radar_driver',
    'WallLineConfig': 'radar_driver',
    'WallLineLocalizer': 'radar_driver',
    'WallPoseObservation': 'radar_driver',
    'calculate_d500_crc8': 'radar_driver',
    'compose_alignment': 'radar_driver',
    'fuse_wall_observation': 'radar_driver',
    'normalize_yaw_cw_deg': 'radar_driver',
    'rebase_calibration_to_start_pose': 'radar_driver',
    'scan_points_in_drone_global': 'radar_driver',
    'NavigationCommandGoal': 'navigation_protocol',
    'COMMAND_NAVIGATE_TO': 'navigation_protocol',
    'COMMAND_STOP_MISSION': 'navigation_protocol',
    'AckStatus': 'navigation_protocol',
    'AuthenticatedFrame': 'navigation_protocol',
    'GroundNavigationProtocol': 'navigation_protocol',
    'NavigationCommandReceipt': 'navigation_protocol',
    'NavigationCommandRejected': 'navigation_protocol',
    'NavigationProtocolError': 'navigation_protocol',
    'RejectReason': 'navigation_protocol',
    'decode_navigation_payload': 'navigation_protocol',
    'encode_navigation_payload': 'navigation_protocol',
    'load_navigation_hmac_key': 'navigation_protocol',
    'pack_authenticated_frame': 'navigation_protocol',
    'pack_navigation_command': 'navigation_protocol',
    'unpack_authenticated_frame': 'navigation_protocol',
    'FakeLCUSRelay': 'relay_lcus',
    'LCUSRelay': 'relay_lcus',
    'RELAY_PORT_ENV': 'relay_lcus',
    'build_channel_command': 'relay_lcus',
    'format_port_list': 'relay_lcus',
    'format_states': 'relay_lcus',
    'list_serial_ports': 'relay_lcus',
    'parse_status_response': 'relay_lcus',
    'resolve_relay_settings': 'relay_lcus',
}
__all__ = tuple(_EXPORT_MODULES)

def __getattr__(name: str):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = _import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value

def __dir__():
    return sorted(set(globals()) | set(_EXPORT_MODULES))
